### ISSUE TITLE
Colocando pra rodar

### ISSUE THREAD

**Issue by contatoaugusto** [forpdi/forpdi#1]
Olá. Bom dia
Como faço pra realmente colocar esse projeto pra funcionar, pra testar, pra vê como funciona? Onde fica os scripts de criação do banco de dados? Aliás qual o banco de dados homologado e que o sistema está preparado pra rodar?
Onde teria uma documentação de deploy?

Obrigado

**Comment by renatorroliveira** [comment]
Olá @contatoaugusto,

Atualmente estamos em processo de elaboração dessa documentação, mas já posso te dar alguns guidelines se quiser rodar esse projeto localmente ou criar uma instância em um servidor de sua escolha.

O sistema utiliza o maven para realizar o build do arquivo .war, então você precisa editar o arquivo pom.xml e inserir no os dados de seu servidor no profile `prd`, então realiza o build do arquivo .war com:

```bash
mvn clean package -P prd
```

Esse arquivo .war estará em `target/forpdi.war` e deve ser implantado utilizando o servidor de aplicação [Wildfly](http://download.jboss.org/wildfly/9.0.2.Final/wildfly-9.0.2.Final.zip) versão 9.0.2. Você deve ter no servidor também a JDK versão 1.8 instalada.

O Banco de Dados que o sistema suporta oficialmente é o MySQL versão 5.7.x. Porém, como ele utiliza o Hibernate e JPA você poderia tentar utilizá-lo com outro banco de dados SQL. A criação das tabelas é feita automaticamente pelo Hibernate ao realizar deploy da aplicação, uma vez que ainda não fizemos o release da versão 1.0.

Vamos publicar a documentação de deploy e outras instruções aqui no GitHub assim que estiverem prontas. Enquanto isso pode perguntar aqui que vamos te orientando.

**Comment by contatoaugusto** [comment]
Muito bom. Ótima explicação. Dessa forma consigo rodar aqui.
Renato, outra pergunta: a proposta ForPDI é que a gente com usuário e senha acesse a aplicação de vocês via Web e preencha o PDI ou é pra cada cliente rodar mesmo a aplicação localmente?

Obrigado mais uma vez

**Comment by renatorroliveira** [comment]
Nós estamos disponibilizando uma instância da aplicação para as universidades utilizarem através de -e-mail e senha, com um domínio próprio só com as informações dela. Por exemplo, [a UNIFAL utiliza um domínio próprio nessa instância](http://unifal.forpdi.org/#/comunidade). Se você quer utilizar nessa instância com um domínio `exemplo.forpdi.org` [solicite o acesso através do site](http://www.forpdi.org/aPlataforma.php).

Caso sua instituição não seja contemplada ou vocês prefiram ter o sistema dentro da infraestrutura de vocês, implante um instância em algum servidor da instituição. Se esse for o caso pode perguntar aqui que damos as instruções para tal.
