### ISSUE TITLE
Fluxo de criação de usuário via Usuários -> Cadastrar

### ISSUE THREAD

**Issue by lgallindo** [forpdi/forpdi#10]
Quando um usuário é cadastrado via Usuários -> Cadastrar, é impossível posteriormente inserir CPF, pois o campo CPF está vazio e desativado na tela de edição.

Sem atualizar CPF, também não é possível atualizar nenhum outro campo do usuário, incluindo resetar a senha.

**Comment by gustavomelo10** [comment]
Olá @lgallindo 

Realizamos testes na plataforma e vimos que esta funcionalidade está funcionando corretamente, conforme pode ser visto na imagem abaixo:

![image](https://user-images.githubusercontent.com/28953578/27299621-4a2ffa4a-5503-11e7-962b-5a6c769cf71d.png)

A parte em que a edição se encontra bloqueada é na visualização do usuário, sendo necessário clicar no botão de edição, conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/28953578/27299736-b9bb416c-5503-11e7-87e9-3ab7de5d6433.png)

Peço que tente novamente, e persistindo o problema nos responda detalhando melhor o problema, de preferência utilizando imagens.
