### ISSUE TITLE
Erro na mensagem de exclusão de uma política com plano vinculado

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#101]
Não posso excluir uma Política que tem um plano vinculado. O sistema não está deixando isso, porém a mensagem deveria ser diferente da que está aparecendo. A mensagem não deve ser de confirmação de exclusão e sim alertando que ele não pode deletar uma política sem deletar os planos vinculados antes.

![sem titulo](https://user-images.githubusercontent.com/28953578/53986924-349bb000-40fe-11e9-932a-726a1b0a0a3d.png)

**Comment by almeidaevt** [comment]
Testei novamente e está ok.
