### ISSUE TITLE
Nova política ou plano não aparecem no menu

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#102]
Às vezes 	quando crio uma nova política ou um novo plano a opção só aparece no menu principal depois que recarrego a página. O usuário poderá achar que algum problema ocorreu na criação. Quando criar uma política ou plano deverá aparecer em seguida a opção no menu, sem precisar de recarregar a página.

![sem titulo](https://user-images.githubusercontent.com/28953578/53987029-7f1d2c80-40fe-11e9-8c0f-33087c88883d.png)

**Comment by REBECANONATO** [comment]
Após algumas criações de Planos e Políticas as opções de criar novos planos e políticas não aparece mais:


![novas políticas e novos planos](https://user-images.githubusercontent.com/38442994/54125352-889ae300-43e3-11e9-8250-177fcbd53bca.png)

**Comment by e7alves** [comment]
> Após algumas criações de Planos e Políticas as opções de criar novos planos e políticas não aparece mais:
> 
> ![novas políticas e novos planos](https://user-images.githubusercontent.com/38442994/54125352-889ae300-43e3-11e9-8250-177fcbd53bca.png)

Não foi possível reproduzir o problema

**Comment by almeidaevt** [comment]
Testei novamente e está ok.
