### ISSUE TITLE
Documento de exportação com logo do ForPDI

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#104]
O documento está sendo exportado com o logo do ForPDI onde deveria ser exportado com o logo do ForRisco.

![sem titulo](https://user-images.githubusercontent.com/28953578/53987211-24380500-40ff-11e9-92e4-9ceb692526a0.png)

**Comment by e7alves** [comment]
O logo do forpdi aparece porquê a URL da logo está setada como 'http://ufla.teste.forpdi.org'. Antes, caso a URL não estivesse setada, não aparecia nenhum logo, agora deverá aparecer o logo do forrico
