### ISSUE TITLE
Cancelar Edição de um Plano de Risco

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#107]
Quando clico para cancelar a edição de um plano de risco nada acontece. Quando clicar nesse botão, a aba deverá fechar e voltar para as Informações gerais do plano em questão.

![sem titulo](https://user-images.githubusercontent.com/28953578/53987414-b04a2c80-40ff-11e9-86c1-4af3db859a2a.png)

**Comment by RaynorFalx** [comment]
Funcionalidade adicionada
