### ISSUE TITLE
Criação de um item dentro de Plano

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#108]
Quando crio um item dentro de Plano a árvore não está atualizando, só atualiza depois que dou um f5 na página. Está acontecendo a mesma coisa para quando deleto um ítem.

![sem titulo](https://user-images.githubusercontent.com/28953578/53987565-2484d000-4100-11e9-8cc7-9f3a27ed74c1.png)

**Comment by RaynorFalx** [comment]
Correção efetuada.
