### ISSUE TITLE
Problema na alteração entre as abas de plano e unidades

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#114]
Quando estou na aba unidades e quero mudar para a aba de Plano tenho que clicar 2x para atualizar a árvore de Plano, caso contrário ficar aparecendo as opções da árvore de Unidades na aba de Plano.

![sem titulo](https://user-images.githubusercontent.com/28953578/54029901-c4863c00-4188-11e9-8643-134e348ee0c9.png)

**Comment by matheus0392** [comment]
Issue já corrigida.
