### ISSUE TITLE
Melhoria para salvar ou cancelar um processo na unidade

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#119]
Colocar o cursor “pointer” para quando o usuário colocar o mouse em cima dos botões de salvar e cancelar um processo.

![sem titulo](https://user-images.githubusercontent.com/28953578/54030310-f64bd280-4189-11e9-8d62-4526a8ef51e0.png)

**Comment by RaynorFalx** [comment]
Botão corrigido
