### ISSUE TITLE
A funcionalidade de adicionar item fecha quando clico no botão salvar

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#127]
Caso eu clicar no botão de salvar na funcionalidade de adicionar novo campo (item) dentro de planos, os campos fecham e mostra a mensagem dizendo que existem erros no formulário. Essa funcionalidade está funcionando corretamente dentro de políticas, fazer o mesmo para planos.

![image](https://user-images.githubusercontent.com/6883430/54054784-e653e300-41c9-11e9-871e-bd8206f22028.png)

![image](https://user-images.githubusercontent.com/6883430/54054798-ec49c400-41c9-11e9-937e-d46244887d4f.png)

**Comment by RaynorFalx** [comment]
Correções efetuadas
