### ISSUE TITLE
Abas são ocultadas quando possui muitas

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#128]
Está dando erro quando tem muitas abas abertas e você clica no número para exibir as ocultas. Aparece uma caixa branca sem nenhum conteúdo.

![image](https://user-images.githubusercontent.com/6883430/54063304-4bb7cc00-41ea-11e9-9c5d-2eb5161ce2c2.png)

**Comment by RaynorFalx** [comment]
Funcionalidade corrigida
