### ISSUE TITLE
Não está cadastrando processo dentro das unidades e subunidades

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#129]
O sistema não está permitindo cadastros de processos dentro de unidades e subunidades. Está retornando a seguinte mensagem: "Erro inesperado: could not execute statement"

![image](https://user-images.githubusercontent.com/6883430/54063492-6c345600-41eb-11e9-9ae6-dd14b5bfd163.png)

**Comment by cristianofatec** [comment]
Prezados, gostaria que postassem a solução aqui. No meu sistema continua dando este mesmo erro
