### ISSUE TITLE
Não está exportando relatório de Plano

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#130]
Quando clico para exportar ou pré-visualizar o relatório dentro de plano está retornando a seguinte mensagem: {"success":false}

![image](https://user-images.githubusercontent.com/6883430/54063643-8458a500-41ec-11e9-8576-a890e770c009.png)

**Comment by REBECANONATO** [comment]
A exportação só ocorre **erro**, quando para o Determinado plano **não** existe Itens e/ou SubItens cadastrados.

**Comment by REBECANONATO** [comment]
O erro ainda ocorre:

![exportacao 0](https://user-images.githubusercontent.com/38442994/54636377-1a01f900-4a65-11e9-9f3f-bada109c7682.png)


![exportacao 1](https://user-images.githubusercontent.com/38442994/54636300-e9ba5a80-4a64-11e9-8ddd-fbce0865fa7f.png)


pré visualização

![exportacao 2](https://user-images.githubusercontent.com/38442994/54636386-1cfce980-4a65-11e9-9ef2-0fc5985c9c85.png)

exportacao

![exportacao 3](https://user-images.githubusercontent.com/38442994/54636406-25edbb00-4a65-11e9-85ba-d7c9fce2d71a.png)

**Comment by matheus0392** [comment]
Related #181
