### ISSUE TITLE
Erro ao acessar uma política (não mostra as informações gerais e aparece "editar plano")

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#131]
Quando acesso uma política pelo menu não aparece as informações gerais na aba que abre. Além disso, se eu clicar para editar aparece "Editar plano".

![image](https://user-images.githubusercontent.com/6883430/54078206-086d6400-42a3-11e9-83f1-e13b69f8567a.png)

Se eu clicar em "Editar plano" por exemplo, fica um loading infinito.
![image](https://user-images.githubusercontent.com/6883430/54078199-e5db4b00-42a2-11e9-8a61-daf0bdcecb4f.png)

**Comment by REBECANONATO** [comment]
Retestado com Sucesso
