### ISSUE TITLE
Erro de exportação da matriz de riscos no documento

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#134]
O relatório com todos os itens selecionados foi exportado, porém, conforme anexo, a matriz de riscos foi apresentada em todos os itens e as respectivas descrições dos itens não foram exportadas.

[PGR UFPA.pdf](https://github.com/forpdi/forpdi/files/2952465/PGR.UFPA.pdf)

(solicitação enviada por validador da UFPA)

**Comment by REBECANONATO** [comment]
Ao efetuar a exportação de Relatório, as informações foram carregadas corretamente.
Porém dentro do arquivo contém um erro:

![Issue 134](https://user-images.githubusercontent.com/38442994/54535499-6e29b200-496d-11e9-9f93-01c71d65b87d.png)
