### ISSUE TITLE
Exclusão de unidade não atualiza na árvore

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#138]
Após excluir uma unidade ou subunidade a árvore não atualizada automaticamente.

**Comment by REBECANONATO** [comment]
Na exclusão, o Menu Lateral fica alterando entre os Menus das políticas, Assim, nem sempre após a exclusão, o menu retorna para o correto.

![tela exlusão 1](https://user-images.githubusercontent.com/38442994/54533805-ca8ad280-4969-11e9-8d52-1ff7a64733fe.png)
![tela exlusão 2](https://user-images.githubusercontent.com/38442994/54533817-d1b1e080-4969-11e9-8c51-12edfee89ac5.png)
![tela exlusão 3](https://user-images.githubusercontent.com/38442994/54533830-d8405800-4969-11e9-9ca6-6e32f80bb8a2.png)
![tela exlusão 4](https://user-images.githubusercontent.com/38442994/54533835-dd050c00-4969-11e9-9500-286ebbc13be5.png)
![tela exlusão 5](https://user-images.githubusercontent.com/38442994/54533843-e2625680-4969-11e9-9d47-3e0ca572ef58.png)

**Comment by e7alves** [comment]
@REBECANONATO não consegui reproduzir o erro
