### ISSUE TITLE
Loading infinito na edição de informações gerais da política

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#140]
Quando tento editar as informações na página inicial da política dá um loading infinito na página.

![image](https://user-images.githubusercontent.com/28953578/54157206-99b91380-4426-11e9-9853-1a73154337a9.png)

![image](https://user-images.githubusercontent.com/28953578/54157217-a0478b00-4426-11e9-9892-5040637bf757.png)

![image](https://user-images.githubusercontent.com/28953578/54157227-a50c3f00-4426-11e9-9bf9-ba9161e7a2a7.png)

**Comment by REBECANONATO** [comment]
Retestado com sucesso.
