### ISSUE TITLE
Logout não redireciona para tela de login

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#141]
Ao sair do sistema (menu>sair), o mesmo não redireciona para uma tela de login, continuando dentro do ForRisco.

![image](https://user-images.githubusercontent.com/28953578/54203319-d598bb00-44b0-11e9-8379-c54b516ec7cd.png)

Obs: apesar de continuar dentro do sistema, nenhum link funciona. Dessa forma é necessário um F5 para retornar para a tela de login.

**Comment by REBECANONATO** [comment]
Retestado com sucesso.
