### ISSUE TITLE
A busca no plano não retorna nada

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#143]
- [ ] A busca no plano não está funcionando. Sempre retorna 0 resultados, mesmo para buscas simples.

![image](https://user-images.githubusercontent.com/28953578/54205193-99fff000-44b4-11e9-94ec-569dcc9af2ae.png)

- [ ] Além disso, após fazer a pesquisa e clicando em outro plano a busca continua, não apresentando a árvore do plano clicado:

![image](https://user-images.githubusercontent.com/28953578/54205581-65406880-44b5-11e9-90ba-c4d9bcd4bfc4.png)

![image](https://user-images.githubusercontent.com/28953578/54205815-d6801b80-44b5-11e9-866b-0e79f54e0f4f.png)

Para mostrar a árvore é necessário clicar no "X" da busca.

**Comment by RaynorFalx** [comment]
"Informações Gerais de um Plano" por definição não se caracteriza como "Item" de um plano sendo assim, buscar por qualquer termo dentro dentro de "Informações Gerais de um Plano" se torna inviável até o momento, sugiro que isso seja cadastrado como uma melhoria.

Os demais pontos da ISSUE foram corrigidos.

**Comment by REBECANONATO** [comment]
Retestado a busca. Para Item e SubItem retorna resultado.
