### ISSUE TITLE
Erro ao clicar em informações gerais de um plano

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#144]
Ao clicar em informações gerais de um plano, o sistema direciona para as informações gerais de outro plano automaticamente.

![image](https://user-images.githubusercontent.com/28953578/54206028-48f0fb80-44b6-11e9-99be-8f51200f2e18.png)

![image](https://user-images.githubusercontent.com/28953578/54206121-6faf3200-44b6-11e9-8375-2cd694942792.png)

**Comment by gustavomelo10** [comment]
Após subir versão o erro não voltou a ocorrer no ambiente de testes. Verificar e se realmente não tiver nada a issue poderá ser fechada.

**Comment by RaynorFalx** [comment]
Funcionalidade corrigida

**Comment by REBECANONATO** [comment]
Retestado com sucesso.
