### ISSUE TITLE
Ajuste grafia de 'Selecione' em combos

### ISSUE THREAD

**Issue by MatheusStauffer** [forpdi/forpdi#148]
Nos combos para selecionar Responsável e vincular o Plano a Política, incluir um 'i' no texto padrão, 'Selecone o Responsável' e 'Selecone a Política'. É um detalhe, mas como é algo que os usuários farão bastante, faz sentido propor esse pequeno ajuste.
![Captura de Tela (190)_LI](https://user-images.githubusercontent.com/26288182/54212688-09c8a780-44c2-11e9-9cea-52f6f08503dc.jpg)
![Captura de Tela (189)_LI](https://user-images.githubusercontent.com/26288182/54212701-0c2b0180-44c2-11e9-933d-08d0bbb1f6a6.jpg)

**Comment by RaynorFalx** [comment]
Correção efetuadas
