### ISSUE TITLE
Notificação de confirmação de envio de mensagens

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#149]
Atualmente o sistema não retorna nenhum aviso confirmando (ou não) o envio de mensagens no sistema. Sugiro que a inclusão de uma notificação com o seguinte texto: "Mensagem enviada com sucesso".

![image](https://user-images.githubusercontent.com/28953578/54218696-d0496980-44cc-11e9-922d-8bb086d00b50.png)

Obs: Esta issue também se relaciona ao ForPDI.

**Comment by matheus0392** [comment]
![image](https://user-images.githubusercontent.com/42619360/54225826-4ead0800-44db-11e9-98f8-a61388e2cc96.png)
 mensagem recebida

**Comment by matheus0392** [comment]
inclusive e-mail recebido.

**Comment by cristianofatec** [comment]
Boa tarde! Não estou conseguindo enviar e-mails. Já alterei o arquivo docker.dev.properties, mas sem sucesso
