### ISSUE TITLE
Importação de usuários por .CSV não está funcionando

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#150]
A importação acusa que o arquivo não é compatível, mesmo sendo um CSV.

![image](https://user-images.githubusercontent.com/28953578/54223557-81083680-44d6-11e9-99d0-2d89a5d3d979.png)

Segue imagens de como foram testados o arquivos CSV (nenhum funcionou):

![image](https://user-images.githubusercontent.com/28953578/54223621-a5641300-44d6-11e9-89b0-02871be73e04.png)

![image](https://user-images.githubusercontent.com/28953578/54223639-b01ea800-44d6-11e9-95b4-348e549cdea9.png)

![image](https://user-images.githubusercontent.com/28953578/54223652-b745b600-44d6-11e9-8a6e-83a76891f578.png)

Obs: esse problema também está relacionado ao ForPDI.

**Comment by matheus0392** [comment]
Mudado a mensagem de importação. Ficou decidido que será aberto uma nova issue para melehoria na importação de arquivo .csv

**Comment by matheus0392** [comment]
#156
