### ISSUE TITLE
Problema na inclusão de item na política

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#154]
- [ ] Ao criar um item ou subitem na política, após salvar, a árvore ficou piscando várias vezes e acabou mostrando a árvore de outra política.

![image](https://user-images.githubusercontent.com/28953578/54231579-8b7efc00-44e7-11e9-8d99-f9f18881f3f4.png)

![image](https://user-images.githubusercontent.com/28953578/54231721-cbde7a00-44e7-11e9-9a2b-85af409cdf4a.png)

- [ ] O mesmo ocorre quando deleto o item ou subitem.

- [ ] O mesmo ocorre nos planos de riscos.

**Comment by REBECANONATO** [comment]
O erro permanece. 
Após inclusão de um Item na primeira política. Funcionou corretamente.

porém ao testar em outras, ao atualizar a página, ele carrega o menu da política acima.

Segue anexo Link para Vídeo. A partir de 1 min do vídeo, fica mais evidente o problema ocorrido.

[https://drive.google.com/open?id=1_qJDsM4UEP18hAHwMj4zYYP4wl29Xyca]
