### ISSUE TITLE
Erro ao deletar um item do plano de riscos

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#155]
Ao deletar um item ou subitem do plano de riscos a árvore "pisca" várias vezes e apresenta a seguinte tela:

![image](https://user-images.githubusercontent.com/28953578/54232471-7d31df80-44e9-11e9-8147-f3f3b70a44c5.png)

Sugiro que quando deletado volte para a tela das informações gerais.

**Comment by REBECANONATO** [comment]
Ao realizar a deleção de um Item/SubItem, o mesmo não é retirado das abas em aberto. O que ocorre a mensagem acima, quando se tentar deletar novamente.

![teste_deletar](https://user-images.githubusercontent.com/38442994/54479103-51b83900-47f8-11e9-847f-d5ed7821f9f6.png)


![teste_deletar_2](https://user-images.githubusercontent.com/38442994/54479107-5977dd80-47f8-11e9-9252-1444be7857d9.png)

**Comment by RaynorFalx** [comment]
Correções efetuadas
