### ISSUE TITLE
Cancelamento de criação de unidade e subunidade não funciona

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#157]
Ao abrir a criação de uma nova unidade ou subunidade e tentar cancelar tal criação, o respectivo botão de cancelamento não funciona.

![image](https://user-images.githubusercontent.com/28953578/54300117-f9383000-459a-11e9-8ce5-005eff50042d.png)

Recomendo que após cancelar a aba da criação feche e abra a aba anteriormente acessada.

**Comment by MatheusStauffer** [comment]
Cancelando em subunidade a página de criação é fechada e o espaço de informações fica em branco; a aba referente à criação de nova subunidade não fecha. Ao cancelar em unidade ainda persiste o problema.
Pós-clique 'cancelar criação de subunidade'
![Captura de Tela (198)_LI](https://user-images.githubusercontent.com/26288182/54372497-2f88b480-465a-11e9-8344-809ae4d87f73.jpg)
Pós-clique 'cancelar criação de unidade'
![Captura de Tela (197)](https://user-images.githubusercontent.com/26288182/54372439-13851300-465a-11e9-9bc6-0c4516c11e88.png)
