### ISSUE TITLE
Exclusão de processo em unidade

### ISSUE THREAD

**Issue by MatheusStauffer** [forpdi/forpdi#159]
Ao excluir um processo de uma unidade, o mesmo é deletado, mas não é eliminado imediatamente na tela.
Estágio 1: Pré-clique no ícone 'lixo'
![Captura de Tela (194)](https://user-images.githubusercontent.com/26288182/54366168-f1d25e80-464e-11e9-9778-059bb40b7b76.png)
Estágio 2: Após clicar no ícone 'lixo'
![Captura de Tela (195)](https://user-images.githubusercontent.com/26288182/54366300-2e05bf00-464f-11e9-9191-613db7b53994.png)
Estágio 3: Após refresh na página ou clicar em outro link do sistema e depois voltar para o 
![Captura de Tela (196)](https://user-images.githubusercontent.com/26288182/54366736-eb90b200-464f-11e9-9af4-a2c488ca7fa5.png)

**Comment by cristianofatec** [comment]
Não estou nem conseguindo criar um processo. Dá uma mensagem de erro em vermelho escrito: "Erro inesperado: could not execute statement"
