### ISSUE TITLE
Botão para salvar novo campo no item ou subitem não funciona

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#161]
A criação de item e subitem no plano de riscos está com problema. Não há um padrão: as vezes o item é criado. As vezes o botão "v" não funciona. As vezes ele é criado mas o campo não salva.

![image](https://user-images.githubusercontent.com/28953578/54437807-3b38b180-4714-11e9-8d7b-3cfd39848647.png)

O mesmo ocorre para o botão "x" quando quero cancelar a criação do campo, que também não funciona.

![image](https://user-images.githubusercontent.com/28953578/54437954-8226a700-4714-11e9-8d81-117f84d9f0f2.png)

Por fim, muitas vezes quando o campo é criado e saio do item e volto, os campos criados anteriormente não aparecem na visualização do item.

![image](https://user-images.githubusercontent.com/28953578/54438069-b732f980-4714-11e9-8ca7-03a2b6a02f59.png)

**Comment by REBECANONATO** [comment]
O Botão "v", não atualiza o novo campo criado.
Cliquei diversas vezes, e somente depois de clicarem salvar, ele "criou", vários campos.
Ao testar novemente, a primeira vez funcionou. Porém, No novo campo o erro ocorreu.

![novo item 1](https://user-images.githubusercontent.com/38442994/54637145-b7116180-4a66-11e9-9ad6-cc7807c29b6e.png)
![novo item 2](https://user-images.githubusercontent.com/38442994/54637148-b973bb80-4a66-11e9-83f0-42cc614bb4cd.png)
![novo item 3](https://user-images.githubusercontent.com/38442994/54637150-b973bb80-4a66-11e9-98dd-d4b96c6a8955.png)
![novo item 4](https://user-images.githubusercontent.com/38442994/54637153-baa4e880-4a66-11e9-9f57-9e5da5061249.png)
![novo item 5](https://user-images.githubusercontent.com/38442994/54637155-bc6eac00-4a66-11e9-990a-5d1e19aa542d.png)
