### ISSUE TITLE
inserir imagem no campo de texto de um item está com problema

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#162]
Ao inserir uma imagem no campo de texto de um item de uma política ou plano e salvar, o sistema não mostra o que foi inserido no campo:

![image](https://user-images.githubusercontent.com/28953578/54438866-5d333380-4716-11e9-8788-4d914bb986f3.png)

![image](https://user-images.githubusercontent.com/28953578/54438890-6a502280-4716-11e9-896d-1fe6798ef1d8.png)

O problema aparece tanto na política quanto no plano.

**Comment by TheKipmaster** [comment]
Erro no console do back-end editando um item de um plano: 

`15:49:38,911 WARN  [SqlExceptionHelper  ]  SQL Error: 1406, SQLState: 22001
15:49:38,911 ERROR [SqlExceptionHelper  ]  Data truncation: Data too long for column 'description' at row 1`
