### ISSUE TITLE
"Nome" é obrigatório na criação do plano de riscos mas não é na edição

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#170]
A criação do plano de riscos obriga o usuário a inserir um nome, mas o sistema permite, na edição, que o usuário retire tal nome e deixe o plano sem.

![image](https://user-images.githubusercontent.com/28953578/54452167-320b0d00-4733-11e9-9e26-5f961350aed8.png)

![image](https://user-images.githubusercontent.com/28953578/54452177-3afbde80-4733-11e9-8f74-f9f095bae9a1.png)

![image](https://user-images.githubusercontent.com/28953578/54452192-451ddd00-4733-11e9-9f67-5ceca195c40b.png)

**Comment by RaynorFalx** [comment]
Correção efetuada
