### ISSUE TITLE
Não consigo acessar um incidente pelo painel de bordo

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#178]
Quando clico em um incidente no gráfico de incidentes presentes no painel de bordo, não consigo acessar o incidente clicando no botão "Visualizar", ou seja, clico e não acontece nada.

![image](https://user-images.githubusercontent.com/6883430/54609124-10f73480-4a31-11e9-903f-dabbe8aed79e.png)

**Comment by RaynorFalx** [comment]
Correções efetuadas
