### ISSUE TITLE
Edição de item e subitem com problema

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#188]
As vezes, quando tento editar um item ou subitem do plano, some todos os campos anteriormente criados:
![image](https://user-images.githubusercontent.com/28953578/54685534-cc819c80-4af5-11e9-92bf-0c36021d2fe9.png)

![image](https://user-images.githubusercontent.com/28953578/54685541-d2777d80-4af5-11e9-9a72-82b7993ff966.png)

Além disso, quando clico para inserir um novo campo ele interpreta como se eu tivesse clicado em salvar.

![image](https://user-images.githubusercontent.com/28953578/54685591-efac4c00-4af5-11e9-90b0-e93a2386de07.png)

**Comment by fillypenascimento** [comment]
Issue já resolvida.
