### ISSUE TITLE
Alteração de arquivo adicionado não funciona

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#189]
Ao tentar alterar um arquivo anteriormente inserido em um item ou subitem de política ou plano, o sistema altera o nome na tela, mas sempre abre o primeiro arquivo inserido:

![image](https://user-images.githubusercontent.com/28953578/54687861-5da74200-4afb-11e9-9487-e00839e5e997.png)

![image](https://user-images.githubusercontent.com/28953578/54687897-70217b80-4afb-11e9-9c22-de18e65033bc.png)

![image](https://user-images.githubusercontent.com/28953578/54687905-76175c80-4afb-11e9-8442-bed75c6cd80c.png)

**Comment by fillypenascimento** [comment]
Issue aparentemente já foi resolvida.
