### ISSUE TITLE
Está abrindo um novo campo quando edito um item em Plano

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#195]
Quando estou criando um novo item dentro de plano, salvo esse campo clicando no botão "v" e logo após clico para editá-lo, está abrindo um novo campo para adicionar um campo. Veja o print da tela.

![image](https://user-images.githubusercontent.com/6883430/54755742-62382d00-4bc5-11e9-9824-8379a9ec716a.png)

**Comment by RaynorFalx** [comment]
Funcionalidade Corrigida
