### ISSUE TITLE
Estrutura do XML de "Estrutura de Plano"

### ISSUE THREAD

**Issue by caiosabadin** [forpdi/forpdi#2]
Olá, boa tarde!

Eu gostaria de saber como é possível realizar o cadastro de uma Estrutura de Plano de Meta. Pelo Menu lateral direto, só nós é possível cadastrar uma por importar um arquivo XML. Se for impossível cadastrar esta estrutura pelo sistema, como podemos gerar esse XML para importá-lo?

Muito obrigado pela atenção de vocês :)

**Comment by renatorroliveira** [comment]
Olá @caiosabadin,
A importação de novas estruturas de planos de metas é feita apenas pelo administrador geral do sistema, mas via sistema mesmo. Se você utiliza o sistema na nuvem (.forpdi.org) você teria que solicitar a inclusão da estrutura customizada.

A estrutura pode ser expressa por um XML seguindo o [XSD do sistema](https://github.com/forpdi/forpdi/blob/master/backend-java/src/main/resources/forpdi_structure_1.0.xsd). Existe um exemplo que define a [estrututura elaborada pelo FORPLAD](https://github.com/forpdi/forpdi/blob/master/backend-java/src/main/resources/forplad_2.0.xml).

Qualquer coisa estamos à disposição.

**Comment by caiosabadin** [comment]
Era isso mesmo, @renatorroliveira. Muito obrigado :)

**Comment by DaniellPontes** [comment]
Boa tarde!

O FORPDI está instalado no ambiente computacional da instituição em que trabalho, porém não há estrutura de plano de metas e não consigo encontrar o .xml para importar. O link da postagem anterior está quebrado.
Onde posso encontrá-lo?

**Comment by lmiranda** [comment]
Oq eu precisaria editar no fonte para liberar o cadastro do plano de metas pelo "administrador" e não apenas pelo administrador de sistema

**Comment by cristianofatec** [comment]
Tenho a mesma dúvida da Imiranda

**Comment by arthurd2** [comment]
> Boa tarde!
> 
> O FORPDI está instalado no ambiente computacional da instituição em que trabalho, porém não há estrutura de plano de metas e não consigo encontrar o .xml para importar. O link da postagem anterior está quebrado.
> Onde posso encontrá-lo?

`https://github.com/forpdi/plataforma-for/blob/master/backend-java/src/main/resources/structure_forplad_2.0.xml`

**Comment by arthurd2** [comment]
Então, dado que depois que um Plano de Metas é cadastrado, não se pode mudar sua infraestrutura. 
Acredito que seja um procedimento que deve ser feito com muito planejamento e  parcimônia, por um membro da TI.
Na minha opinião, e peloque implantamos na UFSC, os "Administradores" (normais) membros VIP da equipe que toca o PDI/Riscos, sem ligação com a TI.
Logo teria que ser estudada esta demanda....

**Comment by 336699** [comment]
Link para estrutura definida pelo FORPLAD.

https://github.com/forpdi/plataforma-for/blob/master/backend-java/src/main/resources/forpdi_structure_1.0.xsd
