### ISSUE TITLE
Criação de busca por similaridade

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#207]
Atualmente a busca retorna apenas resultados que se igualam à palavra buscada ou se a palavra buscada estiver contida dentro do resultado (ex: se buscar por "risco" vai retornar "riscos")

Sugiro o aprimoramento da busca de modo que os resultados retornem também palavras similares (busca por similaridade simples), já que atualmente se a pessoa procura por "riscos" a busca não retorna nenhum resultado com "risco".

**Comment by RaynorFalx** [comment]
Funcionalidade aprimorada.
