### ISSUE TITLE
Melhoria no "Elementos orçamentários"

### ISSUE THREAD

**Issue by zunbi001** [forpdi/forpdi#21]
**Melhoria:**
Ao acessar o menu de "Elementos orçamentários", e visualizar a coluna "Quantidade de objetos vinculados" é necessário que alinhe os dados de forma centralizada.
![8 - erro](https://user-images.githubusercontent.com/32335396/32169359-4c682a00-bd57-11e7-923b-e43a699b5838.png)

**Comment by isalvati** [comment]
Verificar com Everton e Renan a necessidade de corrigir essa issue.
