### ISSUE TITLE
Botão de exportar do lado errado (painel de bordo)

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#216]
Sugiro colocar o botão de "Exportar Relatório" no painel de bordo do lado direito, conforme está na especificação. Acredito que ficará melhor, visualmente falando.

![image](https://user-images.githubusercontent.com/6883430/54993076-c2511980-4f9f-11e9-945b-06c2134a768e.png)

**Comment by RaynorFalx** [comment]
Alteração efetuada
