### ISSUE TITLE
Notificações no e-mail com o nome do ForPDI e palavra sem espaçamento

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#220]
Todas as notificações que estão sendo enviadas por e-mail mostram que estão sendo enviadas do ForPDI, seria interessante modificá-las para ForRisco.

Outra coisa, na notificação de monitoramento de um risco, faltou espaço antes e depois do nome do risco. Veja o print abaixo:

![image](https://user-images.githubusercontent.com/6883430/55072789-c72ecf80-506a-11e9-88d7-5855454827c9.png)

**Comment by matheus0392** [comment]
related #219
