### ISSUE TITLE
Melhorar a distribuição da matriz de risco no card

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#221]
A matriz de riscos não está bem distribuída no card. As margens não estão sendo respeitadas e tem muito espaço em branco. Sugiro verificar os protótipos das telas para ver como deveria ficar.

![image](https://user-images.githubusercontent.com/6883430/55073052-7e2b4b00-506b-11e9-9865-5dca4da81368.png)

**Comment by RaynorFalx** [comment]
Matriz corrigida
