### ISSUE TITLE
Exportação de relatório de política sem itens

### ISSUE THREAD

**Issue by e7alves** [forpdi/forpdi#223]
O sistema não permite exportar relatório de uma política sem itens, mostrando a mensagem: 'Erro ao exportar documento. Preencha os campos autor e título, e selecione pelo menos uma seção'.
![issue](https://user-images.githubusercontent.com/22751472/55084396-e0904580-5083-11e9-82c9-944f260032ca.PNG)

**Comment by matheus0392** [comment]
Falta o item de informações gerais?
