### ISSUE TITLE
Deixar campos de texto sem limite de caracteres

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#226]
Deixar os seguintes campos sem limite de caracteres:

- [ ] Área de texto no novo campo de itens e subitens (tanto da política quanto do plano)

![image](https://user-images.githubusercontent.com/28953578/55101736-8a32ff00-50a3-11e9-90c4-2b1f6c390c71.png)

- [ ] "Descrição" das informações gerais da política e do plano.

![image](https://user-images.githubusercontent.com/28953578/55101825-c5cdc900-50a3-11e9-800b-23799933b442.png)

**Comment by matheus0392** [comment]
talvez seja necessário reiniciar a aplicação.
