### ISSUE TITLE
A duplicação do plano não está trazendo os itens e subitens nem as unidades

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#231]
Quando duplico um plano, mesmo marcando os itens que quero (todos ou apenas alguns), o novo plano criado não traz os itens, subitens e nem as unidades do plano anterior.

![image](https://user-images.githubusercontent.com/28953578/55106876-b99b3900-50ae-11e9-85d1-3a2b531c11fe.png)

![image](https://user-images.githubusercontent.com/28953578/55106885-c324a100-50ae-11e9-8011-9a482397bd1b.png)

**Comment by matheus0392** [comment]
Não consegui reproduzir o erro, mesmo pegando o banco de teste no qual foi percebido o erro.
