### ISSUE TITLE
Inserir "*" para o campo obrigatório de upload de arquivo

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#237]
- [ ] Na criação de processos inserir um "*" ao lado da opção "anexar arquivos", já que este é um campo obrigatório, mantando assim o padrão dos outros campo.

![image](https://user-images.githubusercontent.com/28953578/55112924-819af280-50bc-11e9-810a-93d894840374.png)

- [ ] Além disso, melhorar o alinhamento dos campos, conforme print acima.

**Comment by matheus0392** [comment]
Campo não é mais obrigatório
