### ISSUE TITLE
Erro ao duplicar um "Plano"

### ISSUE THREAD

**Issue by zunbi001** [forpdi/forpdi#24]
**Procedimento:**

Ao cadastrar um "Novo Plano"  desmarcando a opção "Utilizar documento de PDI " e clicar em salvar> Clicar no plano criado > Clicar no nome do plano e acessar o menu "ações" > Ir na opção "Duplicar Plano" > Deixar as mesmas configurações e clicar em duplicar. 

**Erro:**

Portanto, criara um "Documento PDI " com um loop infinito.

![10- erro duplicar](https://user-images.githubusercontent.com/32335396/32223975-c54b6a7a-be26-11e7-8720-486d117ecb8f.png)
-
![10- erro duplicar 2](https://user-images.githubusercontent.com/32335396/32224118-4397736a-be27-11e7-9b7b-38369f7404fc.png)

-
![10- erro duplicar 3](https://user-images.githubusercontent.com/32335396/32223986-d21b6552-be26-11e7-831d-d56953e05c35.png)

**Comment by zunbi001** [comment]
Corrigido

**Comment by edneypp** [comment]
Mais detalhes complemetares na issue #26
