### ISSUE TITLE
Usuário nível gerente não pode excluir uma unidade

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#243]
O usuário do tipo gerente está com permissão de excluir uma unidade. Conforme foi especificado, o usuário do nível gerente poderá apenas Editar e Visualizar as unidades e subunidades (https://docs.google.com/document/d/1yWklLnhPyKPu3s9TZ2Wag22G9RyFuxiRgzVL5YpHR_A/edit).

![image](https://user-images.githubusercontent.com/6883430/55231655-152a0b80-5202-11e9-8e3d-8f11ba4341dc.png)

**Comment by RaynorFalx** [comment]
Funcionalidade alterada
