### ISSUE TITLE
Relatório sendo exportando com as numerações das seções erradas

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#244]
Repare no exemplo abaixo. Tenho 5 itens: Informações gerais, Item 1, Item 2, Item 3 e Item 4. A numeração desses itens no documento deveria ficar da seguinte forma:

1- Informações Gerais
2- Item 1
3- Item 2
4- Item 3
5- Item 4

![image](https://user-images.githubusercontent.com/6883430/55232298-cbdabb80-5203-11e9-897c-b9fa3fa28e26.png)

Mas isso não está acontecendo quando se exporta um documento (veja a figura abaixo). Acredito que esta numeração (não é a paginação, é a numeração das seções) está levando em consideração os itens que já foram excluídos.

![image](https://user-images.githubusercontent.com/6883430/55232318-e14fe580-5203-11e9-9043-944b7125b121.png)

**Comment by matheus0392** [comment]
[https://github.com/forpdi/forpdi/commit/e3d0fffede15cf118ae7552929eadf0ab6c7a98e](url)
