### ISSUE TITLE
Matriz de riscos está desconfigurada

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#249]
Quando crio uma matriz de riscos com o rótulo do grau de risco maior que os outros, a matriz está ficando desconfigurada (esteticamente falando) na página de informação da política.

![image](https://user-images.githubusercontent.com/6883430/55352000-3014ae00-5496-11e9-9e92-aa84393fdeef.png)

**Comment by RaynorFalx** [comment]
Matriz de risco corrigida
