### ISSUE TITLE
Descrição da política não gera quebra no texto

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#261]
Na exibição da descrição da política, em informações gerais, o texto não está quebrando, gerando um scroll horizontal:

![image](https://user-images.githubusercontent.com/28953578/55488348-493c6c80-5606-11e9-8ebd-98ac9ef7d631.png)

**Comment by fillypenascimento** [comment]
Commit 25fdc61ba207e05b48a4c38e5160bac862d69087
