### ISSUE TITLE
Script SQL

### ISSUE THREAD

**Issue by joeugenio** [forpdi/forpdi#3]
Boa noite.

Vocês poderiam disponibilizar os scripts de criação do banco de dados e tabelas.
Desde já, agradeço.

**Comment by renatorroliveira** [comment]
Boa noite @joeugenio,
O schema do banco de dados é criado automaticamente quando você faz o deploy e sobe o sistema pela primeira vez, o Hibernate faz isso para facilitar.
Você precisa do script devido à alguma restrição de infra ou para outros fins mais específicos? Se sim podemos gerar um SQL para criação e alimentação dos dados iniciais.

**Comment by joeugenio** [comment]
Boa noite @renatorroliveira.

Estou tendo problemas com o banco ao executar o script standalone.sh do Wildfly, imaginei que poderia ser a falta de alguma tabela, por isso pedi os scripts. Mas vou analisar com mais calma esse problema, já que a base de dados é criada automaticamente.

Gostaria de aproveitar para tirar mais algumas dúvidas:
1 - Após subir o sistema, será necessário logar com algum usuário e senha padrão?
2 - Como eu poderia mudar o endereço do servidor MySql? O arquivo dev.properties não possui uma propriedade para isso (ex. db.url). Precisarei manter a aplicação em um server e o banco em outro.

Agradeço a atenção.

**Comment by renatorroliveira** [comment]
Sim tem um usuário e senha padrão.
E-mail: admin@forpdi.org
Senha: 12345

Quanto à configuração, realmente ela não existe atualmente. Ela está em `backend-java/src/main/resources/hibernate.cfg.xml`.
Vou marcar essa issue e colocar essa parâmetro configurável nas propriedades.

**Comment by renatorroliveira** [comment]
Outra coisa, você precisa criar o Banco de Dados no MySQL com o CREATE DATABASE antes de rodar a aplicação. Vou atualizar isso no README também.

**Comment by joeugenio** [comment]
Muito obrigado @renatorroliveira.

**Comment by renatorroliveira** [comment]
Agora tem o que você precisa no dev.properties/prd.properties =)

**Comment by joeugenio** [comment]
Muito obrigado pelo suporte, @renatorroliveira .
