### ISSUE TITLE
Erro ao preencher campo "Nome" na criação de um novo úsuario

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#32]
**Procedimento:**
Menu superior de opções >> Usuários >> Cadastro de usuários.

![image](https://user-images.githubusercontent.com/30694914/32275712-71a8d02e-bef3-11e7-9683-1429251e0ddc.png)

![image](https://user-images.githubusercontent.com/30694914/32275749-96ec8d44-bef3-11e7-9341-b21f426cfc9a.png)

![image](https://user-images.githubusercontent.com/30694914/32275771-a7a5491e-bef3-11e7-8364-8b5a1f76ce6c.png)

**Erro:**
Campo "nome" não permiti preencher um nome composto e nem um nome com acentos, ex.: José Antônio. Se tentar preencher o campo com o nome citado acima fica da seguinte forma: JosAntnio.

![image](https://user-images.githubusercontent.com/30694914/32275662-3dcb8620-bef3-11e7-8ced-5b6a9f89e697.png)

**Comment by isalvati** [comment]
Corrigido no [commit 186e3788da39124ec74ec07ed0e35f50b7d4b297](https://github.com/forpdi/forpdi/commit/186e3788da39124ec74ec07ed0e35f50b7d4b297)
