### ISSUE TITLE
Instituição vinculada com o domínio não excluí

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#35]
**Procedimento:**
Menu de opção (superior) >> Sistemas >> Tentar excluir uma instituição.
![image](https://user-images.githubusercontent.com/30694914/32551167-c4a09900-c476-11e7-8a29-51d5d605f888.png)

**Erro:**
A seguinte mensagem é exibida, "Instituição deletada com sucesso!", sendo que não deveria retornar essa mensagem.
![image](https://user-images.githubusercontent.com/30694914/32551215-ec8216e2-c476-11e7-8c43-096019110ad2.png)

**Comment by rafaelsplima** [comment]
Favor retestar, pois não consegui reproduzir o erro! @edneypp
