### ISSUE TITLE
Quebra de layout no texto do campo "Situação"

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#38]
**Procedimento:**
Menu superior >> Usuários >> Convidar usuário >> Preencher os campos de cadastro >> Enviar convite.

**Erro:**
Ocorre quebra de layout no texto do campo "Situção".
![image](https://user-images.githubusercontent.com/30694914/32780178-7feae26a-c927-11e7-9967-8d527efd8d0f.png)

**Sugestão:** Reduzir o espaçamento entre os campos "CPF" e "Tipo de Conta".
Exemplo:
![image](https://user-images.githubusercontent.com/30694914/32780488-89ae22ac-c928-11e7-8826-da69cfd77f4e.png)

**Comment by Hemerson-GH** [comment]
Erro ainda persiste!

**Comment by rafaelsplima** [comment]
![image](https://user-images.githubusercontent.com/20342968/35681911-1e6675e2-0746-11e8-869f-5d0b73281c05.png)

**Comment by rafaelsplima** [comment]
![nao-acontece](https://user-images.githubusercontent.com/20342968/35682072-96d51d12-0746-11e8-9885-33e769458038.png)
