### ISSUE TITLE
Como excluir ou arquivar um plano de metas criado em duplicidade?

### ISSUE THREAD

**Issue by lidianecristinasilva** [forpdi/forpdi#4]
Prezados,
estou usando a versão na nuvem. Não aparece opção d excluir ou arquivar um Plano de Metas criados erroneamente.

Cordialmente,

Lidiane
![capturar](https://cloud.githubusercontent.com/assets/28372622/26120299/990cd912-3a46-11e7-8ee4-49857f8a421b.PNG)

**Comment by renatorroliveira** [comment]
Boa noite @lidianecristinasilva!
Essas opções do plano podem ser acessadas através do pequeno ícone ao lado do nome do plano na área principal da tela que você enviou a imagem.

Vou marcar essa issue como melhoria para destacar melhor esse ícone.
Abaixo imagem marcando o ícone que falei:

![Ícone de opções do plano](https://cloud.githubusercontent.com/assets/6683239/26137649/f631714a-3a99-11e7-985a-526c4f66d7bf.png)

**Comment by lidianecristinasilva** [comment]
Oi Renato, obrigada pela resposta.
Ao clicar no ícone que você falou aparece somente a opção de editar informações. E quando abro para editar não aparece opção de excluir ou arquivar.
A opção de arquivar plano de metas só permite arquivar todos os planos, ou seja, perderei tudo que foi cadastrado.
Aproveito para perguntar, porque a estrutura do meu plano aparece como ForPlad? Pelo que verifiquei não há opção de alterar isso.
Segue imagens;
![capturar](https://cloud.githubusercontent.com/assets/28372622/26150194/b6b93a5e-3ad3-11e7-8b21-36274daf39a9.JPG)
![capturar2](https://cloud.githubusercontent.com/assets/28372622/26150199/ba5f2ca4-3ad3-11e7-9fea-e0bb5cfcec95.JPG)

**Comment by ghaborges** [comment]
Olá @lidianecristinasilva 

Essa é a estrutura homologada pelo ForPlad e sugerida para uso pelas instituições, por isso leva o nome do fórum. Não é possível alterar este nome.

Quanto a impossibilidade de exclusão dos planos de metas, foi um requisito levantado pela equipe de coordenação pensando em dar maior segurança às informações que são cadastradas, mas iremos cadastrar como possibilidade de melhoria e analisar a implementação.

Bom dia.

**Comment by lgallindo** [comment]
É possível restringir o acesso de forma que apenas Administradores tenha acesso ao arquivo?

**Comment by gustavomelo10** [comment]
Olá @lgallindo 
Não, porém a edição, criação e exclusão de conteúdo é exclusiva dos administradores e gerentes. Colaboradores apenas visualizam os dados.
