### ISSUE TITLE
Melhoria ao excluir plano de metas

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#42]
**Procedimento:**
Excluir Plano de Meta.

**Melhoria:**
Ao excluir Plano de Meta ele continua aparecendo como existente, ele desaparece da árvore apenas quando a página é reiniciada.

**Comment by RaydsonFerreira** [comment]
Não foi possível reproduzir o erro, sempre que excluído um plano de metas, o mesmo desaparece da árvore automaticamente sem a necessidade de atualizar a página.
