### ISSUE TITLE
Erro ao excluir elemento orçametário 

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#43]
**Procedimento:**

Elementos Orçamentários >> excluir elemento orçamentário cadastrado.

**Erro:**
Após tentar excluir elemento orçamentário a seguinte mensagem é mostrada: ** Não foi possivél deletar, elemento orçamentario possui orçamento relacionado. **, sendo que o mesmo não esta relacionado a nenhum plano de metas.

![image](https://user-images.githubusercontent.com/30694914/33486291-9bfaf352-d690-11e7-81c9-abb0b75fd3c1.png)

**Comment by rafaelsplima** [comment]
Não consegui reproduzir!
