### ISSUE TITLE
Campo "Realizado" do orçamento não permite valor igual ao valor Empenhado

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#44]
**Procedimento**

Plano de Metas >> Eixo temático >> Objetivo >> Orçamento.

**Erro:**
Campo do valor "Realizado" do orçamento não permite valor igual ao valor Empenhado.

**Obs: Verificar se isso pode ou não ocorrer**

**Comment by rafaelsplima** [comment]
![image](https://user-images.githubusercontent.com/20342968/34107528-b99bc7aa-e3e3-11e7-8aee-02da0ef28759.png)

**Comment by rafaelsplima** [comment]
Não acontece aki!
