### ISSUE TITLE
Erro ao cadastrar orçamento em objetivo

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#46]
**Procedimento:**

Plano de Metas >> Eixo temático >> Objetivo >> "cadastrar novo orçamento".

**Erro:**
Ao relacionar um "Elemento Orçamentário" com o orçamento e exibida a seguinte mensagem, "segue a imagem".

![image](https://user-images.githubusercontent.com/30694914/33487389-301ee040-d694-11e7-8210-b3ffcfb5c6d6.png)

Porém quando abre a página de "Elementos Orçamentos" a  **Quantidade de objetivos vinculados** é atualizado.

**Comment by rafaelsplima** [comment]
Não, consegue reproduzir!
