### ISSUE TITLE
Como adicionar novos usuários.

### ISSUE THREAD

**Issue by joeugenio** [forpdi/forpdi#5]
Boa noite @renatorroliveira ,

Consegui subir o sistema e logar com o usuário padrão. Gostaria de saber como adicionar novos usuários ao sistema. A gerência de usuários parece está desativada.

Att
![captura01](https://cloud.githubusercontent.com/assets/7732135/26226080/b1a51ee2-3c00-11e7-927b-04c4028e9c3d.PNG)

**Comment by renatorroliveira** [comment]
No menu superior direito, se clicar no "burger" menu, tem a opção de usuários para gerencia de usuários.

**Comment by joeugenio** [comment]
Obrigado mais uma vez, @renatorroliveira . O problema estava no domínio cadastrado.
