### ISSUE TITLE
Botão de Adicionar novo campo

### ISSUE THREAD

**Issue by Hemerson-GH** [forpdi/forpdi#50]
**Procedimento:**
Documento FORPDI >> Seção Ficha Técnica >> Editar o titulo ou editar qualquer outra coisa nesta seção.

**Erro:**
Ao fazer isso, o botão de Adicionar novo campo desaparece do modal e não aparece mais.

**Modal sem o botão**
![image](https://user-images.githubusercontent.com/30694914/35045918-8e0953cc-fb7c-11e7-9c47-7eb9ace154fd.png)

**Exemplo de como é o modal com o botão**
![image](https://user-images.githubusercontent.com/30694914/35046009-df95a786-fb7c-11e7-914b-57ff06884ac3.png)

**Comment by rafaelsplima** [comment]
Esse campo não aparece em nenhum momento na seção Ficha Técnica e sim  a partir da Seção (Apresentação).
