### ISSUE TITLE
Existe integração com o SIAFI?

### ISSUE THREAD

**Issue by lgallindo** [forpdi/forpdi#54]
Existe alguma proposta de buscar os elementos da LOA (a aba Elementos Orçamentários) direto no SIAFI? Está no roadmap?

**Comment by gustavomelo10** [comment]
A princípio não existe nenhuma proposta de integração com o SIAFI @lgallindo 
Estudaremos a possibilidade, e caso seja viável implantaremos em versões futuras do sistema.

**Comment by lgallindo** [comment]
Nosso Pro-Reitor de Planejamento planeja fazer uso pesado do forpdi esse ano. Tem algum lugar onde eu possa checar os planos para desenvolvimentos futuros?

**Comment by gustavomelo10** [comment]
Olá @lgallindo 
Todos os recursos previamente planejados, e necessários para a gestão do PDI, já foram implementados e disponibilizados. Sendo assim, até o momento não há nenhum planejamento de desenvolvimento futuro para o ForPDI.
Futuras implementações serão disponibilizadas de acordo com o volume de demandas das universidades, não sendo viável a alteração do sistema em demandas esporádicas.

**Comment by lgallindo** [comment]
Vocês aceitam contribuições externas?
