### ISSUE TITLE
WAR não funciona em tomcat?

### ISSUE THREAD

**Issue by gessycaetano** [forpdi/forpdi#55]
Na documentação não faz referência ao tomcat mas gera um WAR.
Tentei fazer funcionar mas apareceram erros devido à bibliotecas não econtradas... Tentei adicioná-las ao arquivo pom.xml mas mesmo assim ainda não consegui fazer funcionar... 
Está no roadmap ao futuramente na documentação alguma forma de fazê-la funcionar em tomcat?

Atenciosamente,

**Comment by renatorroliveira** [comment]
Bom dia.
A plataforma foi desenvolvida utilizando vários componentes do Java EE 7. Com isso, diversas dependências do projeto são especificadas como `provided` no `pom.xml`.
Teoricamente seria possível rodar em Tomcat, desde que seja um Tomcat que suporte e que esteja usando o Java 8.

Para que funcione no Tomcat deve-se remover a referência para o `parent` no POM e incluir as dependências necessárias, que teria que ser analisado o que é fornecido pelo servidor de aplicação Wildfly que o servlet container Tomcat não fornece.

**Comment by gessycaetano** [comment]
Olá
Muito obrigado pelos esclarecimentos!!!
