### ISSUE TITLE
Erro no Newsletter 

### ISSUE THREAD

**Issue by rafael-henrique** [forpdi/forpdi#58]
**Procedimento:**

1. Preencher o campo newsletter:

![11 - newtt](https://user-images.githubusercontent.com/32335396/36379537-c5342200-155d-11e8-94c2-54c7667d820f.png)

-----

2. Clicar em salvar, e em seguida ok : 

![11 - newtt 2](https://user-images.githubusercontent.com/32335396/36379600-050af58e-155e-11e8-8a76-37c56428d4b9.png)

-----

**Erro:**

Ao preencher o campo do Newsletter do site, ao clicar em **ok** na mensagem, o usuário será redirecionado para uma pagina com a seguinte informação:

![11 - newtt 3](https://user-images.githubusercontent.com/32335396/36379678-4e460612-155e-11e8-90bd-5c42a03e0c9f.png)

**Comment by RaydsonFerreira** [comment]
Não consegui reproduzir o erro, na minha máquina funcionou normalmente a função.
