### ISSUE TITLE
Problemas para exportar relatório de Plano de Metas

### ISSUE THREAD

**Issue by lidianecristinasilva** [forpdi/forpdi#6]
Prezados,
esse problema ocorre com vocês também?
Ao gerar um relatório do Plano de Metas o sistema apresenta a seguinte mensagem de erro:
![erro gerar relatorio de objetivos](https://cloud.githubusercontent.com/assets/28372622/26226881/531f383a-3c05-11e7-9c1a-ab968856b0b5.PNG)

**Comment by renatorroliveira** [comment]
@ghaborges @camiladias @isalvati @rodrigof23
