### ISSUE TITLE
Quebra de layout

### ISSUE THREAD

**Issue by rafael-henrique** [forpdi/forpdi#62]
**Melhoria:**

Quebra de layout no plano de metas, ao criar um plano com nome muito longo, como abaixo:

![13 - quebra](https://user-images.githubusercontent.com/32335396/36445905-658bec96-165e-11e8-8016-3ab293d3ba70.png)

**Comment by RaydsonFerreira** [comment]
![image](https://user-images.githubusercontent.com/28969281/36597201-26ca1142-1887-11e8-9e5a-089a30d27e12.png)

O erro já está atualizado, não consegui reproduzir na minha máquina.
