### ISSUE TITLE
Erro ao excluir um plano

### ISSUE THREAD

**Issue by rafael-henrique** [forpdi/forpdi#63]
**Erro:**

Ao excluir toda a hierarquia de um plano, e em seguida for excluir o plano, a opção de **Excluir Plano** não é habilitada, só é habilitada após dar F5.

- A opção não habilitada:

![14 - erro plani](https://user-images.githubusercontent.com/32335396/36446234-795a11fc-165f-11e8-942f-cf2774506dcc.png)

**Obs:** Erro só acontecerá caso a aba do plano macro estiver aberta.

**Comment by erickAAlves** [comment]
Não foi possível reproduzir o erro. Fornecer mais detalhes.
