### ISSUE TITLE
Problemas com o cadastro dos planos e indicadores

### ISSUE THREAD

**Issue by joeugenio** [forpdi/forpdi#7]
Boa tarde, @renatorroliveira .

O sistema instalado a partir do Git não permite o cadastramento dos planos e indicadores, pois a instituição e o domínio cadastrados não são reconhecidos, mesmo já estando cadastrados.
O acesso online disponibilizado diretamente pelo site [ForPDI](http://forpdi.org/) permite estas inclusões. Envio anexo os prints com os comparativos das ferramentas disponibilizadas.

Grato,

![captura02](https://cloud.githubusercontent.com/assets/7732135/26260601/2cd118a2-3ca4-11e7-8559-2ebeb996f452.png)
![captura03](https://cloud.githubusercontent.com/assets/7732135/26260600/2ccc07f4-3ca4-11e7-9781-c37defed98d8.jpg)

**Comment by renatorroliveira** [comment]
Olá @joeugenio 
Essa diferença provavelmente é devido à permissão do usuário logado ou à falta de configuração de um domínio para acesso. Para que essas opções estejam disponíveis, é necessário que primeiramente se cadastre uma empresa utilizando o usuário administrador. Em seguida cadastre-se um domínio para aquela empresa. Depois deve-se atualizar a página para realizar o acesso por este domínio. Além disso, o usuário utilizado para fazer o cadastro deve ter permissão de administrador da instituição no domínio que está sendo acessado.

Vou tentar fazer um tutorial dessas configurações iniciais para que vocês consigam configurar mais facilmente.

**Comment by renatorroliveira** [comment]
Vídeo de instruções iniciais: [https://youtu.be/4INjIqucYRo](https://youtu.be/4INjIqucYRo)

**Comment by joeugenio** [comment]
Muito obrigado por sua ajuda, @renatorroliveira .
