### ISSUE TITLE
[FORRISCO] Duplicação de processos depois que cadastra um novo processo

### ISSUE THREAD

**Issue by almeidaevt** [forpdi/forpdi#75]
Quando eu crio um processo dentro de uma unidade e depois clico para salvar está aparecendo os processos de outras unidades (processos que não está relacionado a unidade em questão). Só depois que dou refresh na página que mostra os processos certos da unidade.

Nesse print mostra os processos listados no momento da criação de um novo processo. Detalhe, esses processos não são dessa unidades e não etão relacionados com ela:
![img1](https://user-images.githubusercontent.com/6883430/53976948-cf889000-40e6-11e9-92c3-8ec50acca972.png)

Depois que dou o refresh na página mostra o processo certo da unidade em questão:
![img2](https://user-images.githubusercontent.com/6883430/53977071-fc3ca780-40e6-11e9-86f1-dabbbee9835d.png)

**Comment by e7alves** [comment]
Não foi possível reproduzir, provavelmente já foi corrigido.

**Comment by almeidaevt** [comment]
Testei novamente e está ok.
