### ISSUE TITLE
Alerta de confirmação desnecessário

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#77]
Quando clico no botão “Cancelar” para voltar para a tela de login, o sistema retorna um alerta para salvar as modificações. O problema que não tem nenhuma ação a ser salva. Sugiro retirar esse alerta.

![sem titulo](https://user-images.githubusercontent.com/28953578/53981749-f4cecb80-40f1-11e9-8375-8663085d0773.png)

**Comment by matheus0392** [comment]
redirecionado dieramente para tela de login após clicar em cancela.
