### ISSUE TITLE
Sistema não envia e-mail de recuperação de senhas

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#79]
O sistema não enviou o e-mail para recuperar a senha. Esperei um tempo e verifiquei a caixa de entrada, spam e lixeira. Porém, nada foi enviado para o meu e-mail.

**Comment by matheus0392** [comment]
Foi possível receber e-mails após a configuração de um servidor de emails. Foram testados 2 servidores de e-mails. É bom observar as configurações do arquivo de propriedades.

**Comment by almeidaevt** [comment]
Testei novamente e está ok.

**Comment by cristianofatec** [comment]
Qual foi a solulção?
