### ISSUE TITLE
Autenticação LDAP

### ISSUE THREAD

**Issue by juvenalmuniz** [forpdi/forpdi#8]
Bom dia!

Primeiramente, gostaria de parabenizá-los pelo produto! A qualidade é **ótima** e certamente nos ajudará  muito aqui na UFMS.

Existe algum plano para utilizar outros métodos de autenticação como, por exemplo, LDAP?

Quais seriam as dificuldades ou cuidados que teríamos que ter caso quiséssemos implementar outros tipos de autenticação?

Novamente, obrigado pelo produto excelente!

**Comment by ghaborges** [comment]
Olá @juvenalmuniz, bom dia.

A curto prazo não há planos para utilizar o LDAP. Com relação aos cuidados/dificuldades, caso decidam por  implementar este tipo de autenticação, seria necessário alterar o pacote core do sistema, algo que não é tão simples.

Caso tenha mais alguma dúvida, estamos a disposição.

**Comment by renatorroliveira** [comment]
Olá @juvenalmuniz 

Sim, autenticação com LDAP pode ser implementada, apesar de não haver planos para isso no momento.
Existem pacotes de autenticação e autorização no módulo core. O sistema só possui autenticação por e-mail e senha atualmente, teríamos que pensar em uma estrutura para múltiplos métodos de autenticação.

Caso tenham interesse em contribuir com o projeto implementando esse tipo de autenticação eu posso ajudar. Eu nunca implementei autenticação LDAP, porém desenvolvi a maior parte da autenticação existente hoje no sistema.

Abs.

**Comment by juvenalmuniz** [comment]
Olá @renatorroliveira e @ghaborges 

Temos interesse sim em contribuir com o projeto e agradeceríamos a sua ajuda!

Eu pude notar, superficialmente, que há um momento que o usuário é autenticado globalmente através de e-mail e senha e um segundo momento no qual é verificado se esse usuário faz parte de um domínio.

Acredito que essa verificação da existência do usuário no domínio faça parte da arquitetura multi tenant utilizada no sistema. Certo?

Até que ponto esse momento da autenticação global influencia outras partes do sistema? Você acha que seria necessário criar/alterar algo na lógica de separação por domínios?

Eu agradeço ajuda de vocês!

Abs.

**Comment by renatorroliveira** [comment]
Olá @juvenalmuniz 
Sim, é devido ao multitenant.
A autenticação global não poderia ser afetada pela configuração de um tenant.
A autenticação via LDAP deve ser ativada por uma configuração em tempo de build do WAR, via arquivo properties.
Já a autorização em um tenant pode ser configurável individualmente, desde que o LDAP esteja habilitado no build. Dessa forma poderia-se autenticar o usuário e criar a atribuição ao domínio caso neste domínio o LDAP esteja ativado.

Não sei se ficou claro o que eu disse, mas acredito que essa parte seria simples uma vez que a integração com o LDAP estivesse pronta.
