### ISSUE TITLE
Rótulo “Selecione a cor representativa”

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#84]
Colocar o rótulo “Selecione a cor representativa” no select de escolha de cor conforme a especificação no documento de requisitos.

![sem titulo](https://user-images.githubusercontent.com/28953578/53985210-d4a30a80-40f9-11e9-9ce2-8f482b703ea8.png)

**Comment by matheus0392** [comment]
adicionado placeholder no campo select de cor.
