### ISSUE TITLE
Problema na geração e atualização da matriz de riscos

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#86]
Depois que eu gero uma matriz o sistema está deixando eu deletar os campos do grau de riscos e mudar as linhas de probabilidade e impacto. Caso o usuário editar esses campos (grau, probabilidade e impacto), a matriz gerada deve ser removida para que o usuário gere uma nova matriz de acordo com as novas configurações. O botão de gerar uma nova matriz não pode sumir como está acontecendo.

![sem titulo](https://user-images.githubusercontent.com/28953578/53985437-5430d980-40fa-11e9-84a9-411eafb32664.png)

**Comment by matheus0392** [comment]
definido limite de input de  linhas e colunas >1 e <6.
matriz removida após editar os camps de grau de risco, probabilidade ou impacto

**Comment by almeidaevt** [comment]
"definido limite de input de linhas e colunas >1 e <6."
>> Ok, funcionando

"matriz removida após editar os camps de grau de risco, probabilidade ou impacto"
>> Ok, funcionando.

Faltou remover a matriz quando altero a quantidade (número) de linhas de probabilidades e impacto. Acontece que, do jeito que está, quando eu aumento ou diminuo a quantidade de linhas de probabilidade e impacto com uma matriz já gerada, ocorre um erro na qual sistema para de criar os campos dinamicamente.
