### ISSUE TITLE
Erro de direcionamento na criação de nova política e/ou acessar política

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#88]
Quando o usuário cria uma nova política ou acessa uma política pelo menu ele é redirecionado para tela abaixo, porém a tela que o usuário deveria ser redirecionado é a tela de “Informações Gerais”. Essa tela que está abrindo nem deveria existir.

![sem titulo](https://user-images.githubusercontent.com/28953578/53985668-02d51a00-40fb-11e9-9134-ef9a3e85916f.png)

**Comment by almeidaevt** [comment]
Testei novamente e está ok.
