### ISSUE TITLE
Exclusão de plano criado erroneamente

### ISSUE THREAD

**Issue by lgallindo** [forpdi/forpdi#9]
Atualmente a única opção é de arquivamento, mesmo para o Administrador. Isso é intencional?

**Comment by gustavomelo10** [comment]
@lgallindo é possível excluir o plano conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/28953578/27297692-4f3f2d5a-54fc-11e7-9052-a455c81b78c3.png)

Vale ressaltar que o plano pode ser excluído apenas quando todos os outros níveis abaixo forem excluídos.
