### ISSUE TITLE
Fechar aba quando finalizada a edição

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#91]
Quando clicar nos botões de “Salvar” e “Cancelar” na tela de edição de uma política, ela deverá voltar para a tela de “Informações gerais” (já está acontecendo isso) e a aba de edição deverá ser fechada (não está acontecendo isso). Para todas as telas de edição do sistema isso deverá acontecer, ou seja, quando clicar no botão de salvar ou cancelar, a aba de edição deverá ser fechada.

![sem titulo](https://user-images.githubusercontent.com/28953578/53986078-f7ceb980-40fb-11e9-935e-f795b118aa5a.png)

**Comment by RaynorFalx** [comment]
Funcionalidade corrigida e melhorada.
