### ISSUE TITLE
Distância dos itens do menu

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#97]
Manter a mesma distância entre os itens do menu principal. No print abaixo dá para perceber que a opção de Painel de Bordo está com uma distância maior.

![sem titulo](https://user-images.githubusercontent.com/28953578/53986529-30bb5e00-40fd-11e9-9bef-24be7f9268fc.png)

**Comment by RaynorFalx** [comment]
Correção Efetuada
