### ISSUE TITLE
Conteúdo das informações gerais sumindo

### ISSUE THREAD

**Issue by gustavomelo10** [forpdi/forpdi#99]
Quando clico na aba de unidades e volto para o plano, o conteúdo das informações gerais do plano está sumindo. Sempre que o usuário clicar em unidades e depois clicar para acessar o plano o conteúdo que irá aparecer no centro deverá ser o último acessado.

![sem titulo](https://user-images.githubusercontent.com/28953578/53986739-c656ed80-40fd-11e9-9633-9e2b4b97f67f.png)

**Comment by almeidaevt** [comment]
Testei novamente e está ok.
